- id: '1672929641555'
  alias: Set home location from GPS
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.rut955_gps_latitude_coordinate
    - sensor.rut955_gps_longitude_coordinate
  condition: []
  action:
  - service: homeassistant.set_location
    data:
      latitude: '{{ states(''sensor.rut955_gps_latitude_coordinate'') }}

        '
      longitude: '{{ states(''sensor.rut955_gps_longitude_coordinate'') }}

        '
  mode: single
- id: '1675266193319'
  alias: Btn dinette toggle dinette and lounge
  description: ''
  trigger:
  - device_id: 58f044f416251b0d8080e76433616480
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - type: toggle
    device_id: b9d3b7dae8376197aaac6a09a3168452
    entity_id: light.dinette
    domain: light
  - type: toggle
    device_id: 67e73540bdc3a27991dea0554ade67c7
    entity_id: light.lounge
    domain: light
  mode: single
- id: '1675266335902'
  alias: Btn dinette dbl toggle galley
  description: ''
  trigger:
  - device_id: 58f044f416251b0d8080e76433616480
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - type: toggle
    device_id: f7603e249e43a97a0c3820e129031f74
    entity_id: light.galley
    domain: light
  mode: single
- id: '1676750477946'
  alias: Set Inverter State
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_select.inverter_switch_request
  condition: []
  action:
  - service: modbus.write_register
    data:
      hub: cerbo
      slave: 227
      address: 33
      value: '{% if is_state("input_select.inverter_switch_request", "Charger Only")
        %}

        1

        {% elif is_state("input_select.inverter_switch_request", "Inverter Only")
        %}

        2

        {% elif is_state("input_select.inverter_switch_request", "On") %}

        3

        {% elif is_state("input_select.inverter_switch_request", "Off") %}

        4

        {% endif %}

        '
  mode: single
- id: '1678026953905'
  alias: Set Highest PV
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.victron_pv_dc_coupled_power
  condition:
  - condition: numeric_state
    entity_id: sensor.victron_pv_dc_coupled_power
    above: input_number.highest_pv_power
  action:
  - service: input_number.set_value
    data:
      value: '{{ states(''sensor.victron_pv_dc_coupled_power'') }}'
    target:
      entity_id: input_number.highest_pv_power
  mode: single
- id: '1679163813439'
  alias: Btn utility toggle utility
  description: ''
  trigger:
  - device_id: c996624dccbd8e59d3ab1630e9b48c23
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      entity_id: light.utility
  mode: single
- id: '1679164883036'
  alias: Btn utility long press
  description: ''
  trigger:
  - device_id: c996624dccbd8e59d3ab1630e9b48c23
    domain: zha
    platform: device
    type: remote_button_long_press
    subtype: remote_button_long_press
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.switch_1
  mode: single
- id: '1679165966279'
  alias: Btn galley short press
  description: ''
  trigger:
  - device_id: 89a64ef4e6d76c4e62d9c7b1158fc9b9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: f7603e249e43a97a0c3820e129031f74
  mode: single
- id: '1679166127374'
  alias: Btn galley dbl click
  description: ''
  trigger:
  - device_id: 89a64ef4e6d76c4e62d9c7b1158fc9b9
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 947d141dbcc1d7260ad408a60a1ca427
  mode: single
- id: '1679211298440'
  alias: Btn lounge short press
  description: ''
  trigger:
  - device_id: f7e34cb3c467697fe5ccaa612dec77c8
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: ba26965bd2187155f65813dbad58d5f7
  mode: single
- id: '1679211552037'
  alias: Btn lounge dbl click
  description: ''
  trigger:
  - device_id: f7e34cb3c467697fe5ccaa612dec77c8
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 67e73540bdc3a27991dea0554ade67c7
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: b9d3b7dae8376197aaac6a09a3168452
  mode: single
- id: '1679666360921'
  alias: Btn bathroom short press
  description: ''
  trigger:
  - device_id: f8add7226cc43065ba0d41a885641f6d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 2bed79d48e31958dd231674236920bb3
  mode: single
- id: '1679666457123'
  alias: Btn bathroom dbl click
  description: ''
  trigger:
  - device_id: f8add7226cc43065ba0d41a885641f6d
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: ba26965bd2187155f65813dbad58d5f7
  mode: single
- id: '1679666760584'
  alias: Btn bed port short press
  description: ''
  trigger:
  - device_id: c6a95799ebd0f560c138cc6e4448554c
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 2bed79d48e31958dd231674236920bb3
  mode: single
- id: '1679666805259'
  alias: Btn bed port dbl click
  description: ''
  trigger:
  - device_id: c6a95799ebd0f560c138cc6e4448554c
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: ba26965bd2187155f65813dbad58d5f7
  mode: single
- id: '1679667092858'
  alias: Btn bed starboard short press
  description: ''
  trigger:
  - device_id: 5d526af78ef7ad832683ebd3e2a42659
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 2bed79d48e31958dd231674236920bb3
  mode: single
- id: '1679667145962'
  alias: Btn bed starboard dbl click
  description: ''
  trigger:
  - device_id: 5d526af78ef7ad832683ebd3e2a42659
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: ba26965bd2187155f65813dbad58d5f7
  mode: single
- id: '1679668004353'
  alias: Btn desk short press
  description: ''
  trigger:
  - device_id: 749db8c66fc6001df75d653b22ebf0c9
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: 2bed79d48e31958dd231674236920bb3
  mode: single
- id: '1679668061402'
  alias: Btn desk dbl click
  description: ''
  trigger:
  - device_id: 749db8c66fc6001df75d653b22ebf0c9
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      device_id: ba26965bd2187155f65813dbad58d5f7
  mode: single
- id: '1679668871304'
  alias: Hatch opened
  description: ''
  trigger:
  - type: opened
    platform: device
    device_id: cf8c687e802019a2bfbee2c089a13ea2
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
  condition:
  - condition: device
    type: is_off
    device_id: 947d141dbcc1d7260ad408a60a1ca427
    entity_id: light.utility
    domain: light
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      device_id: 947d141dbcc1d7260ad408a60a1ca427
  mode: single
- id: '1679680530478'
  alias: Hatch closed
  description: ''
  trigger:
  - type: not_opened
    platform: device
    device_id: cf8c687e802019a2bfbee2c089a13ea2
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_opening
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - service: light.turn_off
    data: {}
    target:
      device_id: 947d141dbcc1d7260ad408a60a1ca427
  mode: restart
- id: '1679683259991'
  alias: Btn utility dbl click
  description: ''
  trigger:
  - device_id: c996624dccbd8e59d3ab1630e9b48c23
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      device_id: bbedb2248ef962ed0ec630e93a4017a4
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.switch_2
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.switch_2
  mode: single
- id: '1679985766975'
  alias: Battery depleted below threshold
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.victron_battery_soc
    below: input_number.shore_power_threshold
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.victron_inverter
      state: Inverter Only
    - condition: state
      entity_id: sensor.victron_inverter
      state: 'Off'
  action:
  - if:
    - condition: state
      entity_id: sensor.victron_inverter
      state: 'Off'
    then:
    - service: modbus.write_register
      data:
        address: 33
        slave: 227
        value: 1
        hub: cerbo
    else:
    - service: modbus.write_register
      data:
        address: 33
        slave: 227
        value: 3
        hub: cerbo
  mode: single
- id: '1679986366744'
  alias: Battery fully charged
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.victron_battery_state
    from: '1'
    to: '0'
  - platform: state
    entity_id:
    - sensor.victron_battery_state
    from: '1'
    to: '2'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.victron_inverter
      state: 'On'
    - condition: state
      entity_id: sensor.victron_inverter
      state: Charger Only
  - condition: numeric_state
    entity_id: sensor.victron_battery_soc
    above: '99'
  action:
  - if:
    - condition: state
      entity_id: sensor.victron_inverter
      state: Charger Only
    then:
    - service: modbus.write_register
      data:
        address: 33
        slave: 227
        value: 4
        hub: cerbo
    else:
    - service: modbus.write_register
      data:
        address: 33
        slave: 227
        value: 2
        hub: cerbo
  mode: single
- id: '1681377294414'
  alias: Turn on electric heater in lounge
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lumi_lumi_weather_temperature
    below: 20
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.heater_outlet_light_2
  mode: single
- id: '1681377387335'
  alias: Turn off heater in lounge
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.lumi_lumi_weather_temperature
    above: 21
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.heater_outlet_light_2
  mode: single
- id: '1682067773070'
  alias: Turn on stern lights at sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    target:
      entity_id: light.stern
  mode: single
- id: '1682067827614'
  alias: When the sun rises turn off the stern lights
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.stern
  mode: single
- id: '1682093581137'
  alias: Table btn toggle pendant
  description: ''
  trigger:
  - device_id: 89da5e22f0c4b539c06843a3cd7b0ef7
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: remote_button_short_press
  condition: []
  action:
  - service: light.toggle
    data: {}
    target:
      entity_id: light.pendant_lamp
  mode: single
- id: '1682094051433'
  alias: Table btn double click dinette lights
  description: ''
  trigger:
  - device_id: 89da5e22f0c4b539c06843a3cd7b0ef7
    domain: zha
    platform: device
    type: remote_button_double_press
    subtype: remote_button_double_press
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 100
    target:
      entity_id: light.dinette
  mode: single
