# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module

frontend:
  themes: !include_dir_merge_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
# alert: !include alerts.yaml
modbus: !include modbus.yaml
template: !include templates.yaml