# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

logger:
  default: info

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /local/text-element.js?v=0
      type: module

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

group: !include groups.yaml
automation: !include automations.yaml
script: !include_dir_merge_named scripts
scene: !include scenes.yaml
# alert: !include alerts.yaml
modbus: !include modbus.yaml
template: !include templates.yaml