
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
#tts:
#  - platform: google_translate
  
homeassistant:
  packages: !include_dir_named packages

lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# alert: !include alerts.yaml
modbus: !include modbus.yaml
template: !include templates.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key