# lovelace_gen
resources:
  - url: !file /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: !file /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: !file /local/royalsignage.css
    type: css

button_card_templates: !include_dir_merge_named "custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

views:
  - !include lovelace/home.yaml
  - !include lovelace/control.yaml
  - !include lovelace/scenes.yaml
  - !include lovelace/monitoring.yaml
  - !include lovelace/location.yaml